### ISSUE TITLE
Update po file on Debian site ?

### ISSUE THREAD

**Issue by Wallon007** [Xubuntu/lightdm-gtk-greeter#108]
Hello,

Would you please update the po files for the translations on the Debian site?

Thank you.

**Comment by bluesabre** [comment]
Debian uses the translations included in the release. Once a new release is published, it will be packaged with the latest translations.

**Comment by Wallon007** [comment]
Dear Bluesabre,

At Debian https://www.debian.org/international/l10n/po/fr
The French version (lightdm-gtk-greeter) is translated at 80%.
In Transifex, French is transladed at 100%.

So the po files have not been updated in Debian.

Best regards,
Wallon
